In [1]:
import tensorflow as tf
x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y + 2
#Reference Figure 9-1

In [2]:
#Utilizing a tensorflow session will help modify our tensorflow graph
#here is our tensorflow session code
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)
print(result)

AttributeError: module 'tensorflow' has no attribute 'Session'

In [3]:
x1 = tf.Variable(1)
x1.graph is tf.get_default_graph()

AttributeError: Tensor.graph is meaningless when eager execution is enabled.

In [4]:
graph = tf.Graph()
with graph.as_default():
    x2 = tf.Variable(2)
x2.graph is graph

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


True

In [5]:
import tensorflow as tf
tf.__version__

'2.0.0'

In [6]:
#Fuck Ch 9 of the old text its TF 1, we have tf 2 so here we go:
#For TF 2 we use TF like Numpy instead of cariables we will use constants
import tensorflow as tf
tf.constant([[1., 2., 3.], [4., 5., 6.]])

<tf.Tensor: id=36, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [7]:
tf.constant(42) #scalar

<tf.Tensor: id=37, shape=(), dtype=int32, numpy=42>

In [8]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t.shape

TensorShape([2, 3])

In [9]:
t.dtype

tf.float32

In [10]:
#We are indexing like in Numpy(Try to find out what indexing in Numpy means)
t[:, 1:]

<tf.Tensor: id=42, shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [11]:
t[..., 1, tf.newaxis]

<tf.Tensor: id=46, shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [12]:
t + 10

<tf.Tensor: id=48, shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [13]:
#What we just did in the previous cel was define our array of t, now we can apply math to it
tf.square(t)

<tf.Tensor: id=49, shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [14]:
#Try to figure out why you have different values, anywho....
t @ tf.transpose(t)

<tf.Tensor: id=52, shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [15]:
#T + 10 is equal to tf.add(t, 10), and can simply use tf.multiply(), tf.square(), tf.sqrt(), tf.reduce_mean
#Now work with Keras
from tensorflow import keras
K = keras.backend
K.square(K.transpose(t)) + 10

<tf.Tensor: id=57, shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

In [16]:
#Tensors flow well with numpy, dont forget to import it
import numpy as np
a = np.array ([2., 4., 5.])
tf.constant(a)

<tf.Tensor: id=58, shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [17]:
t.numpy() #otherwise known as an np.array(t)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [18]:
tf.square(a)

<tf.Tensor: id=60, shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [19]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [20]:
np.square(a)

array([ 4., 16., 25.])

In [21]:
#32 bit precision is more than enough for a neural netowkr and run fast with less RAM
#In general when creating a tensor from a Numpy array, make sure to set dtype=tf.float32
#Now working with type conversions
#Dont worry these are suppose to happen to show conversions are shit
tf.constant(2.) + tf.constant(40)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: add/

In [22]:
tf.constant(2.) + tf.constant(40., dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: add/

In [23]:
#To fix any mode of conversion we will use a cast system
t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: id=68, shape=(), dtype=float32, numpy=42.0>

In [24]:
#Yep casts=fix the "cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: add/" bullshit error
#Now we will be working with outdate variables
v = tf.Variable ([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [25]:
v.assign(2 * v)
v[0, 1].assign(42)
v[:, 2].assign([0., 1.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [26]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>

In [27]:
#Keras provides an add_weight() method to take care of the model parmeters
#Othe rdata structure to fit the model in the data: 
#sparse tensors(tf.SparseTensor)
#tensor arrays(tf.TensorArray)
#ragged tenspors(tf.raggedtensor)
#string tensoirts (tf.string)
#then there are sets and ques

In [28]:
#Customizing models and training
#Creatinign a custom loss function
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abs(error) - 0.5 
#This is a vectorized implementation 

In [29]:
model.compile(loss=huber_fn, optimizer="nadam")
model.fit(X_train, y_train, [...])

NameError: name 'model' is not defined

In [30]:
#This is the tip of the spear to train the model now we can execute 
model = keras.models.load_model("my_model_with_a_custom_loss.h5",
                               custom_objects={"huber_fn": huber_fn})

OSError: SavedModel file does not exist at: my_model_with_a_custom_loss.h5/{saved_model.pbtxt|saved_model.pb}